// <auto-generated />
using System;
using CleanArchitecture.InfraStructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CleanArchitecture.InfraStructure.Migrations
{
    [DbContext(typeof(CleanArchitectureContext))]
    [Migration("20241217172507_adicionar_coluna_tab_categoria")]
    partial class adicionar_coluna_tab_categoria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("CleanArchitecture.Domain.Models.Categoria", b =>
                {
                    b.Property<long>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_CATEGORIA");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT")
                        .HasColumnName("DAT_CADASTRO");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT")
                        .HasColumnName("DESCRICAO");

                    b.HasKey("IdCategoria");

                    b.ToTable("CATEGORIA", (string)null);
                });

            modelBuilder.Entity("CleanArchitecture.Domain.Models.Produto", b =>
                {
                    b.Property<long>("IdProduto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_PRODUTO");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT")
                        .HasColumnName("DATA_CADASTRO");

                    b.Property<string>("Descricao")
                        .HasColumnType("TEXT")
                        .HasColumnName("DESCRICAO");

                    b.Property<long>("IdCategoria")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ID_CATEGORIA");

                    b.Property<string>("Nome")
                        .HasColumnType("TEXT")
                        .HasColumnName("NOME");

                    b.Property<decimal>("Preco")
                        .HasColumnType("TEXT")
                        .HasColumnName("PRECO");

                    b.HasKey("IdProduto");

                    b.HasIndex("IdCategoria");

                    b.ToTable("PRODUTO", (string)null);
                });

            modelBuilder.Entity("CleanArchitecture.Domain.Models.Produto", b =>
                {
                    b.HasOne("CleanArchitecture.Domain.Models.Categoria", "Categoria")
                        .WithMany("Produtos")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("CleanArchitecture.Domain.Models.Categoria", b =>
                {
                    b.Navigation("Produtos");
                });
#pragma warning restore 612, 618
        }
    }
}
